<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Couldn\'t create new contractor or product on row {row}.' => 'Zapisanie nowego kontrahenta lub produktu w wierszu {row} nie powiodło się.',
    'Couldn\'t create new order item on row {row}.' => 'Zapisanie nowej linii zamówienia w wierszu {row} nie powiodło się.',
    'Couldn\'t create new order on row {row}.' => 'Zapisanie nowego zamówienia w wierszu {row} nie powiodło się.',
    'Process' => 'Proces',
    'Set your column order' => 'Ustaw kolejność kolumn',
    'Statuses of same order are different on row {row},' => 'Statusy tego samego zamówienia różnią się.',
];
