<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Failed to save uploaded file.' => 'Nie udało się załadować pliku.',
    'Method returned exception type {type} with message {message}' => 'Metoda zwróciła wyjątek typu {type} z komunikatem {message}',
    'Parser class must extend from Parser model.' => 'Klasa parsera musi rozszerzać model Parser.',
    'Parser has to be set.' => 'Parser musi być ustawiony.',
    'Process' => 'Przetwarzaj',
    'Set your column order' => 'Podaj porządek kolumn',
];
