<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acknowledged On' => 'Potwierdzono dnia',
    'Author ID' => 'ID autora',
    'Browse Files' => 'Przeglądaj pliki',
    'Browse Messages' => 'Przeglądaj wiadomości',
    'Browse Parsers' => 'Przeglądaj parsery',
    'Browse Transactions' => 'Przeglądaj transakcje',
    'Class' => 'Klasa',
    'Confirm Date' => 'Data potwierdzenia',
    'Content' => 'Zawartość',
    'Create File' => 'Utwórz plik',
    'Create Message' => 'Utwórz wiadomość',
    'Create Parser' => 'Utwórz parser',
    'Create Transaction' => 'Utwórz transakcję',
    'Created On' => 'Utworzono dnia',
    'Currency' => 'Waluta',
    'Delete File' => 'Usuń plik',
    'Delete Message' => 'Usuń wiadomość',
    'Delete Parser' => 'Usuń parser',
    'Delete Transaction' => 'Usuń transakcję',
    'Delivment' => 'Delivment',
    'Dev Date' => 'Dev date',
    'Editor ID' => 'ID edytora',
    'Entry Date' => 'Data wprowadzenia',
    'File' => 'Plik',
    'File ID' => 'ID pliku',
    'Filename' => 'Nazwa pliku',
    'Files' => 'Pliki',
    'First Column' => 'Pierwsza kolumna',
    'First Row' => 'Pierwszy wiersz',
    'Hash' => 'Skrót',
    'ID' => 'ID',
    'Incoterms' => 'Incoterms',
    'Is Disabled' => 'Jest nieaktywny',
    'Is Import' => 'Jest importem',
    'Item Buyer' => 'Kupujący',
    'Item Description' => 'Opis przedmiotu',
    'Item Number' => 'Numer przedmiotu',
    'Items Count' => 'Liczba elementów',
    'Last Confirm Date' => 'Ostatnia data potwierdzenia',
    'Line' => 'Linia',
    'Message' => 'Wiadomość',
    'Messages' => 'Wiadomości',
    'Metkj' => 'Metkj',
    'Mimetype' => 'Typ MIME',
    'Name' => 'Nazwa',
    'Number' => 'Numer',
    'Order Number' => 'Numer zamówienia',
    'Parser' => 'Parser',
    'Parser Class' => 'Klasa parsera',
    'Parser Configuration' => 'Konfiguracja parsera',
    'Parser ID' => 'ID parsera',
    'Parser Options' => 'Opcje parsera',
    'Parsers' => 'Parsery',
    'Processed Count' => 'Liczba przetworzonych',
    'Processed On' => 'Przetworzono dnia',
    'Quantity' => 'Ilość',
    'Request Date' => 'Data żądania',
    'Request ID' => 'ID żądania',
    'Sent On' => 'Wysłano dnia',
    'Sheet' => 'Arkusz',
    'Size' => 'Rozmiar',
    'Status' => 'Status',
    'Subline' => 'Podlinia',
    'Supplier Item Code' => 'Kod przedmiotu dostawcy',
    'Supplier Item Description' => 'Opis przedmiotu dostawcy',
    'Supplier Name' => 'Nazwa dostawcy',
    'Supplier Number' => 'Numer dostawcy',
    'Transaction' => 'Transakcja',
    'Transaction ID' => 'ID transakcji',
    'Transactions' => 'Transakcje',
    'Unit Price' => 'Cena jednostkowa',
    'Update File' => 'Aktualizuj plik',
    'Update Message' => 'Aktualizuj wiadomość',
    'Update Parser' => 'Aktualizuj parser',
    'Update Transaction' => 'Aktualizuj transakcję',
    'Updated On' => 'Zaktualizowano dnia',
    'Upload files' => 'Wczytaj pliki',
    'Url' => 'URL',
    'View File' => 'Szczegóły pliku',
    'View Message' => 'Szczegóły wiadomości',
    'View Parser Configuration' => 'Szczegóły konfiguracji parsera',
    'View Transaction' => 'Szczegóły transakcji',
];
