<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acknowledged On' => 'Potwierdzono dnia',
    'Author ID' => 'ID autora',
    'Browse Files' => 'Przeglądaj pliki',
    'Browse Messages' => 'Przeglądaj wiadomości',
    'Browse Parser Configurations' => 'Przeglądaj konfiguracje parsera',
    'Browse Transactions' => 'Przeglądaj transakcje',
    'Columns Order' => 'Porządek kolumn',
    'Content' => 'Zawartość',
    'Create File' => 'Utwórz plik',
    'Create Message' => 'Utwórz wiadomość',
    'Create Parser Configuration' => 'Utwórz konfigurację parsera',
    'Create Transaction' => 'Utwórz transakcję',
    'Created On' => 'Utworzono dnia',
    'Delete File' => 'Usuń plik',
    'Delete Message' => 'Usuń wiadomość',
    'Delete Parser Configuration' => 'Usuń konfigurację parsera',
    'Delete Transaction' => 'Usuń transakcję',
    'Delimiter' => 'Separator',
    'Editor ID' => 'ID edytora',
    'Enclosure' => 'Opakowanie',
    'Escape' => 'Znak unikowy',
    'File' => 'Plik',
    'File ID' => 'ID pliku',
    'File Messages' => 'Wiadomości pliku',
    'Filename' => 'Nazwa pliku',
    'Files' => 'Pliki',
    'First Column' => 'Pierwsza kolumna',
    'First Row' => 'Pierwszy wiersz',
    'Hash' => 'Skrót',
    'Header' => 'Nagłówek',
    'ID' => 'ID',
    'Is Disabled' => 'Jest nieaktywny',
    'Is Import' => 'Jest importem',
    'Items Count' => 'Liczba elementów',
    'Length' => 'Długość',
    'Message' => 'Wiadomość',
    'Messages' => 'Wiadomości',
    'Mimetype' => 'Typ MIME',
    'Name' => 'Nazwa',
    'Number' => 'Numer',
    'Parser Class' => 'Klasa parsera',
    'Parser Configuration' => 'Konfiguracja parsera',
    'Parser Configurations' => 'Konfiguracje parsera',
    'Parser ID' => 'ID parsera',
    'Parser Options' => 'Opcje parsera',
    'Processed Count' => 'Liczba przetworzonych',
    'Processed On' => 'Przetworzono dnia',
    'Request ID' => 'ID żądania',
    'Sent On' => 'Wysłano dnia',
    'Sheet' => 'Arkusz',
    'Size' => 'Rozmiar',
    'Transaction' => 'Transakcja',
    'Transaction ID' => 'ID transakcji',
    'Transactions' => 'Transakcje',
    'Transaction Messages' => 'Wiadomości transakcji',
    'Type' => 'Rodzaj',
    'Update File' => 'Aktualizuj plik',
    'Update Message' => 'Aktualizuj wiadomość',
    'Update Parser Configuration' => 'Aktualizuj konfigurację parsera',
    'Update Transaction' => 'Aktualizuj transakcję',
    'Updated On' => 'Zaktualizowano dnia',
    'Upload files' => 'Wczytaj pliki',
    'Url' => 'URL',
    'View File' => 'Szczegóły pliku',
    'View Message' => 'Szczegóły wiadomości',
    'View Parser Configuration' => 'Szczegóły konfiguracji parsera',
    'View Transaction' => 'Szczegóły transakcji',
];
