<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acknowledged On' => 'Potwierdzono dnia',
    'Author ID' => 'ID autora',
    'Browse Files' => 'Przeglądaj pliki',
    'Browse Messages' => 'Przeglądaj wiadomości',
    'Browse Parsers' => 'Przeglądaj parsery',
    'Browse Transactions' => 'Przeglądaj transakcje',
    'Class' => 'Klasa',
    'Content' => 'Zawartość',
    'Create File' => 'Utwórz plik',
    'Create Message' => 'Utwórz wiadomość',
    'Create Parser' => 'Utwórz parser',
    'Create Transaction' => 'Utwórz transakcję',
    'Created On' => 'Utworzono dnia',
    'Delete File' => 'Usuń plik',
    'Delete Message' => 'Usuń wiadomość',
    'Delete Parser' => 'Usuń parser',
    'Delete Transaction' => 'Usuń transakcję',
    'Editor ID' => 'ID edytora',
    'File' => 'Plik',
    'File ID' => 'ID pliku',
    'Filename' => 'Nazwa pliku',
    'Files' => 'Pliki',
    'Hash' => 'Skrót',
    'ID' => 'ID',
    'Is Import' => 'Jest importem',
    'Items Count' => 'Liczba elementów',
    'Message' => 'Wiadomość',
    'Messages' => 'Wiadomości',
    'Mimetype' => 'Typ MIME',
    'Number' => 'Numer',
    'Parser' => 'Parser',
    'Parser Class' => 'Klasa parsera',
    'Parser ID' => 'ID parsera',
    'Parser Options' => 'Opcje parsera',
    'Parsers' => 'Parsery',
    'Processed Count' => 'Liczba przetworzonych',
    'Processed On' => 'Przetworzono dnia',
    'Request ID' => 'ID żądania',
    'Sent On' => 'Wysłano dnia',
    'Size' => 'Rozmiar',
    'Transaction' => 'Transakcja',
    'Transaction ID' => 'ID transakcji',
    'Transactions' => 'Transakcje',
    'Update File' => 'Aktualizuj plik',
    'Update Message' => 'Aktualizuj wiadomość',
    'Update Parser' => 'Aktualizuj parser',
    'Update Transaction' => 'Aktualizuj transakcję',
    'Updated On' => 'Zaktualizowano dnia',
    'Url' => 'URL',
    'View File' => 'Szczegóły pliku',
    'View Message' => 'Szczegóły wiadomości',
    'View Parser' => 'Szczegóły parsera',
    'View Transaction' => 'Szczegóły transakcji',
];
